---
-
  hosts: all
  sudo: True
  vars:
    # projectname: vagrant-test
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

# SSH Keys

    # - authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    # - authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    # - name: hello world
    #   action: command touch hello-world.txt

    - name: Set hostname to 'your-machine-name'
      hostname: name=your-machine-name

# System Tools

    - apt: pkg=build-essential
    - apt: pkg=g++
    - apt: pkg=libssl-dev
    - apt: pkg=figlet
    - apt: pkg=ntp
    - apt: pkg=curl
    - apt: pkg=git-core
    - apt: pkg=vim
    - apt: pkg=ufw
    - apt: pkg=python-software-properties

# PHP

    - name: PHP
      apt: pkg=php5
    - name: PHP - Pear
      apt: pkg=php-pear

# HHVM

    - name: Add HHVM Repo
      apt_repository: repo='ppa:mapnik/boost' state=present
    - name: Add HHVM Repo Key
      apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
    - name: Add HHVM Repo Source
      shell: echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
    - name: Install HHVM
      apt: pkg=hhvm update_cache=yes

# Apache

    - name: Apache
      apt: pkg=apache2
    - apt: pkg=apache2-utils
    - apt: pkg=libapache2-mod-php5
    - apache2_module: state=present name=rewrite
    - apache2_module: state=present name=ssl

# MySQL

    - name: MySQL
      apt: pkg=mysql-server

# Memcache

    - name: Memcache
      apt: pkg=memcached

    - name: PHP Modules
      apt: pkg=php5-mysql
      apt: pkg=php5-memcached
      apt: pkg=beanstalkd
      apt: pkg=php5-json
      apt: pkg=php5-curl
      apt: pkg=php5-gd
      apt: pkg=php5-xmlrpc
      apt: pkg=php5-intl
      apt: pkg=php5-mcrypt

    # - name: PHP ENMOD
    #   command: php5enmod mcrypt
    #   command: php5enmod mysql
    #   command: php5enmod memcached
    #   command: php5enmod json
    #   command: php5enmod curl
    #   command: php5enmod gd
    #   command: php5enmod xmlrpc
    #   command: php5enmod intl

# # NODE
# # curl https://raw.github.com/creationix/nvm/master/install.sh | sh
# # source ~/.profile
# # nvm install 0.10.24
# # nvm alias default 0.10.24
    # - npn: name=grunt-cli global=yes
    # - npn: name=bower global=yes
    # - npn: name=forever global=yes
    # - npn: name=mocha global=yes

#     # - apt: pkg=ruby1.9.1-dev
#     # - apt: pkg=postfix
#     - gem: name=sass state=present # version=1.0
#     - gem: name=compass state=present # version=1.0

    # - name: Firewall - HTTP
    #   ufw: rule=allow name=http
    # - name: Firewall - HTTPS
    #   ufw: rule=allow name=https
    # - name: Firewall - SSH
    #   ufw: rule=allow name=ssh
    # - name: Firewall
    #   ufw: state=enabled

# # SYS SETUP
#     - command: ntpdate ntp.ubuntu.com
#     - service: name=ntp state=started

# # curl -sS https://getcomposer.org/installer | php
# # sudo mv composer.phar /usr/local/bin/composer

# # sudo pear config-set auto_discover 1
# # sudo pear install pear.phpunit.de/phpunit

#     - composer: command=install working_dir=/vagrant prefer_source=yes # no_dev=no optimize_autoloader=no


# # sudo reboot
